# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-09 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
